Resources:
  DynamoMonoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DynamoMonoTable-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: HASH
          AttributeType: S
        - AttributeName: RANGE
          AttributeType: S
        - AttributeName: LSIRANGE
          AttributeType: S
        - AttributeName: GSI0HASH
          AttributeType: S
        - AttributeName: GSI0RANGE
          AttributeType: S
        - AttributeName: GSI1HASH
          AttributeType: S
        - AttributeName: GSI1RANGE
          AttributeType: S
        - AttributeName: GSI2HASH
          AttributeType: S
        - AttributeName: GSI2RANGE
          AttributeType: S
      KeySchema:
        - AttributeName: HASH
          KeyType: HASH
        - AttributeName: RANGE
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI
          KeySchema:
            - AttributeName: HASH
              KeyType: HASH
            - AttributeName: LSIRANGE
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: GSI0
          KeySchema:
            - AttributeName: GSI0HASH
              KeyType: HASH
            - AttributeName: GSI0RANGE
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1HASH
              KeyType: HASH
            - AttributeName: GSI1RANGE
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2HASH
              KeyType: HASH
            - AttributeName: GSI2RANGE
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
